### ISSUE TITLE
SSL support is not available. Cannot connect over SSL

### ISSUE THREAD

**Issue by moigagoo** [fox0430/nicoru#15]
1. Install nicoru with `nimble install nicoru`
2. Run `sudo nicoru run archlinux`

Expected: command run.

Actual: 
```
$ sudo nicoru run archinux
httpclient.nim(865)      newConnection
Error: unhandled exception: SSL support is not available. Cannot connect over SSL. Compile with -d:ssl to enable. [HttpRequestError]
```

My setup is Arch Linux on WSL2 on Windows 10.

**Comment by fox0430** [comment]
@moigagoo 

Thank you. I'll fix it soon.

**Comment by fox0430** [comment]
@moigagoo 

Probably already fixed by #14

**Comment by moigagoo** [comment]
Thanks for the quick response and for the great project! Wish you all the luck with it.

**Comment by fox0430** [comment]
@moigagoo 

Thank you very much! 
Please feel free to ask me.
